//ADD Tasks
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS";
export const MESSAGE_TODO_FAILER="MESSAGE_TODO_FAILER";

export const REMOVE_TODO_SUCCESS ="REMOVE_TODO_SUCCESS";

//Fetch Tasks
export const FETCH_TODO_SUCCESS="FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILER="FETCH_TODO_FAILER";


//checked
export const CHECKED_TODO_SUCCESS="CHECKED_TODO_SUCCESS";

//for Chart
export const CHART_START="CHART_START"
export const CHART_FETCH_DATA_SUCCESS="CHART_FETCH_DATA_SUCCESS"
export const CHART_FETCH_DATA_FAILER="CHART_FETCH_DATA_FAILER"